import { Component } from '@angular/core';
import { BoardcellComponent } from "../boardcell/boardcell.component";

@Component({
  selector: 'app-board',
  standalone: true,
  imports: [BoardcellComponent],
  templateUrl: './board.component.html',
  styleUrl: './board.component.css'
})
export class BoardComponent {
  cells: any = [
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: false },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
    { color: true },
    { color: false },
  ]

}
